general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = hyprlock
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({action = "on"})'
}

listener {
    timeout = 300
    condition_cmd = test "$(cat /sys/class/power_supply/AC0/online)" = "1"
    on-timeout = brightnessctl -s set 6000
    on-resume = brightnessctl -r
}

listener {
    timeout = 60
    condition_cmd = test "$(cat /sys/class/power_supply/AC0/online)" = "0"
    on-timeout = brightnessctl -s set 3000
    on-resume = brightnessctl -r
}

listener {
    timeout = 60
    on-timeout = brightnessctl -sd rgb:kbd_backlight set 0
    on-resume = brightnessctl -rd rgb:kbd_backlight
}

listener {
    timeout = 310
    on-timeout = hyprlock
}

listener {
    timeout = 320
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({action = "off"})'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({action = "on"})'
}

listener {
    timeout = 480
    condition_cmd = test "$(cat /sys/class/power_supply/AC0/online)" = "0"
    on-timeout = systemctl suspend
}
