#!/usr/bin/env bash


if ! command -v fzf &>/dev/null ||
  ! command -v gh &>/dev/null ||
  ! command -v jq &>/dev/null ||
  ! command -v git &>/dev/null ||
  ! command -v stow &>/dev/null;
then
  echo "Starting Nix shell..."
  exec nix \
    --extra-experimental-features "nix-command flakes" \
    shell nixpkgs#git nixpkgs#gh nixpkgs#fzf nixpkgs#stow nixpkgs#jq \
    --command "$0" "$@"
fi

repo_select() {
  repo=$(
    gh repo list --limit 1000 \
      --json nameWithOwner,description \
      --jq '.[] | [.nameWithOwner, (.description // "")] | @tsv' |
    fzf \
      --height 50% \
      --layout=reverse \
      --border \
      --delimiter=$'\t' \
      --with-shell=bash \
      --prompt='Repository: '
  )

  if [[ -n "$repo" ]]; then
    repo=$(cut -f1 <<< "$repo")
    printf "$repo"
  fi
}

define_path() {
  read -er -i $2 -p "$1" path

  if [[ "$path" == "~" || "$path" == "~/"  ]]; then
    path="$HOME"
  elif [[ "$path" == "~/"* ]]; then
    path="$HOME/${path#\~/}"
  fi

  echo "$path"
}

repo_setup() {
  mkdir -p "$2"
  gh repo clone "$1" "$2" -- --depth 1 --single-branch
}

yes_no() {
  read -rp "$1" confirm \
    && [[ -n $confirm && $confirm == [yY] ]] \
    || return 1

  return 0
}

run_disko() {
  sudo nix \
    --experimental-features "nix-command flakes" \
    run github:nix-community/disko/latest -- \
    --mode "$1" "$2"
}

select_provider() {
  PS3="Select a provider: "

  select _PROVIDER in "GitHub"; do
    case "$_PROVIDER" in
      "GitHub")
        break
        ;;
      "")
        echo "Invalid service."
        ;;
      *)
        break
        ;;
    esac
  done

  printf "$_PROVIDER"
}

select_host_config() {
  return $(
    nix --extra-experimental-features "nix-command flakes" \
      eval --json "$1#nixosConfigurations" \
      --apply builtins.attrNames |
      jq -r '.[]' |
      fzf \
        --height 50% \
        --layout=reverse \
        --border \
        --delimiter=$'\t' \
        --with-shell=bash \
        --prompt='Available config hosts: '
  )
}

gh_auth_or_die() {
  if ! gh auth status &>/dev/null; then
    echo "Not logged into GitHub CLI. Starting auth:"
    gh auth login

    if ! gh auth status &>/dev/null; then
      echo "GitHub auth not successful. Exiting..."
      exit 1
    fi
  fi
}

format_and_install() {
  echo "Select the NixOS config repo."
  _PROVIDER="$(select_provider)"

  if [[ "$_PROVIDER" == "GitHub" ]]; then
    gh_auth_or_die

    echo "Select NixOS repo"
    _NIXOS_REPO="$(repo_select)"
    echo "NixOS repo: $_NIXOS_REPO"
    _NIXOS_TARGET="$(define_path "NixOS target path: " "${_NIXOS_REPO##*/}")"
    _NIXOS_TARGET="$(realpath "$_NIXOS_TARGET")"
    echo "Cloning the NixOS repo."
    repo_setup "$_NIXOS_REPO" "$_NIXOS_TARGET"

    clear
    echo "Select host configuration:"
    _NIXOS_HOST="$(select_host_config "$_NIXOS_TARGET")"
    _HOST_PATH="$_NIXOS_TARGET/hosts/$_NIXOS_HOST"

    if [[ -d "$_HOST_PATH" ]]; then
      echo "Host '$_NIXOS_HOST' selected."

      if [[ -f "$_HOST_PATH/disko-config.nix" ]]; then
        echo "Disko disk config detected. Use it to wipe your disk and reformat."
        echo "That would wipe all your existing data on that disk."

        if yes_no "Format the disk using disko? (y/N): "; then
          echo "Wiping disk and reformatting."
          run_disko destroy,format,mount "$_HOST_PATH/disko-config.nix"
        else
          echo "Skipping reformatting."
          run_disko mount "$_HOST_PATH/disko-config.nix"
        fi
      else
        echo "No disko config found."
      fi

      echo "Running nixos-install:"
      echo "sudo nixos-install --flake $_NIXOS_TARGET#$_NIXOS_HOST"

      sudo nixos-install --flake "$_NIXOS_TARGET#$_NIXOS_HOST"

      echo "Installation successful."
      post_install
    else
      echo "Host '$_NIXOS_HOST' not found."
      echo "$_HOST_PATH doesn't exist"
      exit 1
    fi
  else
    echo "Only GitHub currently supported. Exiting."
    exit 1
  fi
}

post_install() {
  if [[ -z $_PROVIDER ]]; then
    _PROVIDER="$(select_provider)"
  fi

  if [[ "$_PROVIDER" == "GitHub" ]]; then
    gh_auth_or_die

    _NEW_USER_HOME="$(define_path "New user's home directory: " "/mnt/home/")"

    echo "Select the public repo:"
    _PUBLIC_REPO="$(repo_select)"
    echo "Public repo: $_PUBLIC_REPO"
    _PUBLIC_TARGET="$(define_path "Public target path: " "$_NEW_USER_HOME/configs/${_PUBLIC_REPO##*/}")"

    echo "Select the private repo (optional, Ctrl+C to skip):"
    _PRIVATE_REPO="$(repo_select)"

    if [[ -n "$_PRIVATE_REPO" ]]; then
      echo "Private repo: $_PRIVATE_REPO"
      _PRIVATE_TARGET="$(define_path "Private target path: " "$_NEW_USER_HOME/configs/${_PRIVATE_REPO##*/}")"
    else
      _PRIVATE_TARGET=
      echo "Skipping private repo."
    fi

    if [[ -z $_NIXOS_REPO ]]; then
      echo "Select NixOS repo"
      _NIXOS_REPO="$(repo_select)"
    fi

    echo "NixOS repo: $_NIXOS_REPO"
    _NIXOS_TARGET="$(define_path "NixOS target path: " "$_NEW_USER_HOME/configs/${_NIXOS_REPO##*/}")"

    echo "Cloning the public repo."
    repo_setup "$_PUBLIC_REPO" "$_PUBLIC_TARGET"

    if [[ -n "$_PRIVATE_REPO" ]]; then
      echo "Cloning the private repo."
      repo_setup "$_PRIVATE_REPO" "$_PRIVATE_TARGET"
    fi

    echo "Cloning the NixOS repo."
    repo_setup "$_NIXOS_REPO" "$_NIXOS_TARGET"

    if [[ -f "$_PUBLIC_TARGET/.config/nos/config" ]]; then
      echo "Detected nos config in the public repo."
      if read -p "Copy it to ~/.config/nos/config.local? (Y/n): " confirm \
        && [[ -z $confirm || $confirm == [yY] || $confirm == [yY][eE][sS] ]];
      then
        mkdir -p "$_NEW_USER_HOME/.config/nos"
        _LOCAL_CFG="$_NEW_USER_HOME/.config/nos/config.local"
        cp "$_PUBLIC_TARGET/.config/nos/config" "$_LOCAL_CFG"
        echo "Copied nos config to $_LOCAL_CFG"

        if [[ -n "$_NIXOS_HOST" ]]; then
          echo "Select host configuration:"
          _NIXOS_HOST="$(select_host_config "$_NIXOS_TARGET")"
        fi

        sed -i "s/^NIXOS_BUILD_HOSTNAME=$/NIXOS_BUILD_HOSTNAME=$_NIXOS_HOST/" "$_LOCAL_CFG"
        source "$_LOCAL_CFG"
        git -C "$_PUBLIC_TARGET" remote set-url origin "$PUBLIC_REPO"

        if [[ -n "$_PRIVATE_REPO" && -n "$PRIVATE_REPO" ]]; then
          git -C "$_PRIVATE_TARGET" remote set-url origin "$PRIVATE_REPO"
        fi

        if [[ -n "$NIXOS_REPO" ]]; then
          git -C "$_NIXOS_TARGET" remote set-url origin "$NIXOS_REPO"
        fi
      fi
    fi

    echo "Running stow on the public and private repos."
    stow -d "$_PUBLIC_TARGET" -t "$_NEW_USER_HOME" --no-folding .
    stow -d "$_PRIVATE_TARGET" -t "$_NEW_USER_HOME" --no-folding .

    if [[ -d "$_NEW_USER_HOME/.ssh" ]]; then
      chmod 600 "$_NEW_USER_HOME/.ssh"/*
    fi

    echo "That's all folks. Bye!"
  else
    echo "Only GitHub currently supported. Exiting."
    exit 1
  fi
}

if [[ "$1" == "post" ]]; then
  post_install
else
  format_and_install
fi
