#!/usr/bin/env bash


SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/lib/util.sh"
source "$SCRIPT_DIR/lib/repos.sh"

if [[ $# -lt 1 ]]; then
  usage
  exit 1
fi

_FUNCTION="$1"
shift

ARGS_REST=()
_DRY_RUN=
_WITH_YES=
_WITH_STOW=

while [[ $# -gt 0 ]]; do
  case "$1" in
    --config)
      if [[ $# -lt 2 ]]; then
        echo "Missing value for $1"
        exit 1
      fi

      CFG_PATH="$2"
      shift 2
      ;;
    --dry-run)
      _DRY_RUN=1
      shift
      ;;
    -y|--yes)
      _WITH_YES=1
      shift
      ;;
    *)
      ARGS_REST+=("$1")
      shift
      ;;
  esac
done

if [[ "$_FUNCTION" == "sample-config" ]]; then
  sample_config
  exit 0
fi

_WITH_LOCAL_CONFIG=1

if [[ -f "$CFG_PATH" ]]; then
  CFG_PATH="$(realpath "$CFG_PATH")"
  _WITH_LOCAL_CONFIG=
else
  CFG_PATH="$HOME/.config/nos/config"
fi

_CFG_LOADED=

if [[ -f "$CFG_PATH" ]]; then
  info "$(style "dim" "Sourcing configuration from $(style "path" "$CFG_PATH")")"
  source "$CFG_PATH"
  _CFG_LOADED=1
fi

CFG_LOCAL_PATH="$HOME/.config/nos/config.local"

if [[ -n "$_WITH_LOCAL_CONFIG" && -f "$CFG_LOCAL_PATH" ]]; then
  info "$(style "dim" "Local config detected in $(style "path" "$CFG_LOCAL_PATH")")"
  source "$CFG_LOCAL_PATH"
  _CFG_LOADED=1
fi

if [[ -z "$_CFG_LOADED" ]]; then
  missing_config
  exit 1
fi

if [[ -n "$STOW_TARGET" ]]; then
  STOW_TARGET="$(realpath "$STOW_TARGET")"
fi

if command -v stow &>/dev/null; then
  _WITH_STOW=1
fi

case "$_FUNCTION" in
  init)
    init_repos
    ;;
  update)
    latest_all
    ;;
  stow)
    stow_or_die

    if [[ ${#ARGS_REST[@]} -eq 0 ]]; then
      stow_all
      exit
    fi

    case "${ARGS_REST[0]}" in
      public)
        stow_public
        ;;
      private)
        stow_private
        ;;
      *)
        error "Unknown repo $(style "action" "${ARGS_REST[0]}")."
        exit 1
        ;;
    esac
    ;;
  auto-update)
    _NIXOS_BIN="/run/current-system/sw/bin"

    if [[ -d "$_NIXOS_BIN" ]]; then
      # If it's run from a service on NixOS, systemd restricts the enviroment.
      # Padding the PATH to see git and stow.
      PATH="$_NIXOS_BIN:$PATH"
    fi

    latest_all

    if [[ "$AUTO_UPDATE_STOW" != "1" ]]; then
      info "Stow disabled for $(style "action" "auto-update")."
      info i "Set AUTO_UPDATE_STOW=1 inside your config to enable it."
      exit
    fi

    stow_or_die
    stow_all
    ;;
  service)
    if [[ ${#ARGS_REST[@]} -eq 0 ]]; then
      error "No service action specified."
      exit 1
    fi

    case "${ARGS_REST[0]}" in
      start)
        info "Starting service timer..."
        systemctl --user start nos-auto-update.timer
        ;;
      stop)
        info "Stopping service timer..."
        systemctl --user stop nos-auto-update.timer
        ;;
      status)
        systemctl --user status nos-auto-update.service
        ;;
      log)
        journalctl --user -f -u nos-auto-update.service
        ;;
      *)
        error "Unknown service action $(style "action" "${ARGS_REST[0]}")."
        exit 1
        ;;
    esac
    ;;
  help)
    usage
    ;;
  os)
    if [[ ${#ARGS_REST[@]} -eq 0 ]]; then
      error "No OS action specified."
      exit 1
    fi

    case "${ARGS_REST[0]}" in
      build)
        if command -v nixos-rebuild &>/dev/null; then
          error "$(style "command" "nixos-rebuild") not detected. Do you even NixOS?"
          info i "You should really be on NixOS...btw"
          exit 1
        fi

        if [[ -z "$NIXOS_PATH" ]]; then
          error "NixOS path not set."\
            "$(style "option" "NIXOS_PATH") in the config."
          exit 1
        fi

        if [[ -z "$NIXOS_BUILD_HOSTNAME" ]]; then
          error "NixOS build hostname not set."\
            "$(style "option" "NIXOS_BUILD_HOSTNAME") in the config."
          exit 1
        fi

        if [[ "$_DRY_RUN" == "1" ]]; then
          info "Dry run. Would have executed the following:"
          echo "$(styled_build)"
        else
          if [[ "$_WITH_YES" != "1" ]]; then
            info "About to rebuild NixOS:"
            info i "$(styled_build)"
            read -p "  Continue? (Y/n): " confirm\
              && [[ "$confirm" == "" || $confirm == [yY] || $confirm == [yY][eE][sS] ]]\
              || exit
          fi

          sudo nixos-rebuild switch --flake "$NIXOS_PATH#$NIXOS_BUILD_HOSTNAME"
        fi
        ;;
      *)
        error "Unknown OS action $(style "action" "${ARGS_REST[0]}")."
        exit 1
        ;;
    esac
    ;;
  *)
    echo "Unknown function $(style "command" "$_FUNCTION")" >&2
    exit 1
    ;;
esac
